version: '3'
services:
  frontend:
    image: frontend/exercise-tracker:1.0
    build: ./frontend
    command: "yarn start"
    ports:
      - 3001:3000
    depends_on:
      - "backend"
  backend:
    image: backend/exercise-tracker:1.0
    build: ./backend
    command: "node server.js"
    ports: 
      - 5001:5000
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mern-exercise-tracker
