version: '3'
services:
  frontend:
    image: frontend/exercise-tracker:1.0
    build: ./frontend
    stdin_open: true
    command: "yarn start"
    ports:
      - 3000:3000
    networks:
      - mern-app
    
  backend:
    image: backend/exercise-tracker:1.0
    build: ./backend
    command: "node server.js"
    ports: 
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge

  
