version: '3.1'

services:
  frontend:
    image: frontend/exercise-tracker
    build: frontend
    stdin_open: true
    command: "yarn start"
    ports:
      - 3000:3001
  backend:
    image: backend/exercise-tracker
    build: backend
    command: "node server.js"
    ports: 
      - 5000:5000
    environment:
      MONGO_DB: ${MONGODB_APP_USER}
      MONGO_DB_USERNAME: ${MONGODB_APP_USER}
      MONGO_DB_PWD: ${MONGODB_APP_PASSWORD}
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      - $MONGO_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DB}
      MONGODB_APP_USER: ${MONGODB_APP_USER}
      MONGODB_APP_PASSWORD: ${MONGODB_APP_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ${PWD}/db/init.js:/docker-entrypoint-initdb.d/init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
